KP-758, KP-759, KP-760 [Ansible] method Run Playbook doesn't cwd so playbook cannot run properly
Kaholo/kaholo-plugin-ansible pull request #13
Opened 2022-05-26 16:12 UTC by xkcm

[**KP-758 in Jira**](https://kaholo.atlassian.net/browse/KP-758)
[**KP-759 in Jira**](https://kaholo.atlassian.net/browse/KP-759)
[**KP-760 in Jira**](https://kaholo.atlassian.net/browse/KP-760)

2022-05-28 14:04 UTC, kenskyfish approved these changes
Looks really nice. There's just one small issue about how to secure the SSH key, with easy workarounds. I put it in the backlog.

2022-05-29 09:03 UTC, kenskyfish submitted a review, later dismissed

2022-05-30 07:02 UTC, graddaniel requested changes

2022-05-30 07:02 UTC, graddaniel commented on ansible-cli.js
> +    updatedParams.vaultPasswordFile = `$${volumeConfigsMap.get("vaultPasswordFile").mountPoint}`;
Since `updatedParams` and `params` share the reference, this line will update both of them. Clone the object, to avoid source object mutation.

2022-05-30 07:02 UTC, graddaniel commented on ansible-cli.js
> +    cwd: `$${volumeConfigsMap.get("playbookDirectory").mountPoint}`,
Please avoid abbreviations when not strongly justified and recommended.

2022-05-31 10:10 UTC, kenskyfish submitted a review, later dismissed
Still looks good to me

2022-05-31 10:43 UTC, graddaniel requested changes
One more thing

2022-05-31 10:43 UTC, graddaniel commented on ansible-cli.js
> +      vaultPasswordFile: updatedParams.vaultPasswordFile,
Now its visible that only three of the original params are required here, and only one of them might be mutated. In such case `clone` is an overkill, and the intent can be clearly expressed with a creation of an object which:
- Has three params, read from the original object.
- With one of the params value set conditionally
I conclude that the object will contain `ansibleCommandParams`

2022-05-31 12:16 UTC, graddaniel approved these changes

2022-06-01 05:37 UTC, merged